server:
  port: 8000


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        #- id: customer
         # uri: lb://CUSTOMER
          #predicates:
           # - Path=/api/v1/customers/**
  main:
    web-application-type: reactive


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true