server:
  port: 8000


spring:
  application:
    name: gateway
  main:
    web-application-type: reactive


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true